"""added name to projectmember

Revision ID: 0780be6f552c
Revises: ed4af4b4f364
Create Date: 2024-11-11 20:39:31.763547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0780be6f552c'
down_revision = 'ed4af4b4f364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
