"""changes

Revision ID: a2c036404d16
Revises: ed4af4b4f364
Create Date: 2024-11-11 22:03:43.126549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c036404d16'
down_revision = 'ed4af4b4f364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        # Add a foreign key constraint with a name
        batch_op.create_foreign_key(
            'fk_projects_column_name',  # Constraint name
            'other_table',  # The referenced table
            ['column_name'],  # The columns in the current table (projects)
            ['other_column_name']  # The columns in the referenced table
        )

        # Add a unique constraint with a name
        batch_op.create_unique_constraint(
            'uq_projects_column_name',  # Constraint name
            ['column_name']  # The column to which the unique constraint applies
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        # Drop foreign key constraint by name
        batch_op.drop_constraint('fk_projects_column_name', type_='foreignkey')

        # Drop unique constraint by name
        batch_op.drop_constraint('uq_projects_column_name', type_='unique')


    # ### end Alembic commands ###
